# Generated by Django 5.1.6 on 2025-11-05 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulacionRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latencia_actual', models.FloatField(help_text='Latencia actual en ms')),
                ('perdida_paquetes_actual', models.FloatField(help_text='Pérdida de paquetes actual en %')),
                ('ancho_banda_actual', models.FloatField(help_text='Ancho de banda actual en Mbps')),
                ('trafico_pico', models.FloatField(help_text='Tráfico en hora pico en Gbps')),
                ('num_usuarios', models.IntegerField(help_text='Número de usuarios concurrentes')),
                ('servicio_pmaas', models.BooleanField(default=False, verbose_name='PMaaS')),
                ('servicio_cdn', models.BooleanField(default=False, verbose_name='CDN IPTV')),
                ('servicio_ddos', models.BooleanField(default=False, verbose_name='Anti DDoS')),
                ('servicio_analisis', models.BooleanField(default=False, verbose_name='Análisis de Tráfico')),
                ('latencia_mejorada', models.FloatField(blank=True, null=True)),
                ('perdida_paquetes_mejorada', models.FloatField(blank=True, null=True)),
                ('ancho_banda_mejorado', models.FloatField(blank=True, null=True)),
                ('mejora_porcentual', models.FloatField(blank=True, null=True)),
                ('analisis_ia', models.TextField(blank=True, null=True)),
                ('recomendaciones_ia', models.TextField(blank=True, null=True)),
                ('costo_estimado_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('roi_estimado_meses', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ip_cliente', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simulación de Red',
                'verbose_name_plural': 'Simulaciones de Red',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
